site_name: jsourceprofiler Docs
site_description: |
  jsourceprofiler is a command-line profiler for Java programs using source code instrumentation.
  The single JAR-file utility generates HTML reports enabling hotspot analysis and providing coverage with line counts. 
  It features an optional JavaFX tool-runner GUI.

repo_url: https://github.com/matwoess/jsourceprofiler
repo_name: matwoess/jsourceprofiler

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - JavaFX UI: fxui.md
  - Report: report.md
  - Implementation Details: implementation-details.md
  - Runtime Impact: runtime-impact.md
  - Limitations: limitations.md
  - Dependencies: dependencies.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference