name: "CI"

on:
  # OS parameter for reusable workflow
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  unittests:
    name: "Run unit tests (${{ inputs.os }})"
    runs-on: ${{ inputs.os }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: "Execute Gradle 'test' task"
        continue-on-error: true
        run: |
          ./gradlew test

      - name: "Upload Gradle report - tool"
        uses: actions/upload-artifact@v4
        with:
          name: gradle-report-tool-${{ inputs.os }}
          path: jsourceprofiler-tool/build/reports/tests/

      - name: "Upload Gradle report - common"
        uses: actions/upload-artifact@v4
        with:
          name: gradle-report-common-${{ inputs.os }}
          path: jsourceprofiler-common/build/reports/tests/

      - name: "Upload JUnit results - tool"
        uses: dorny/test-reporter@v1
        with:
          name: "JUnit results - tool (${{ inputs.os }})"
          path: jsourceprofiler-tool/build/test-results/test/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

      - name: "Upload JUnit results - common"
        uses: dorny/test-reporter@v1
        with:
          name: "JUnit results - common (${{ inputs.os }})"
          path: jsourceprofiler-common/build/test-results/test/TEST-*.xml
          reporter: java-junit
          fail-on-error: false
