name: "MkDocs Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Install Python Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: "Generate Javadocs"
        run: ./gradlew aggregateJavadoc

      - name: "Copy Javadoc to docs"
        run: |
          mkdir -p docs/docs/api
          cp -r build/docs/javadoc/* docs/docs/api

      - name: "Generate Dark-Style Javadocs"
        run: ./gradlew aggregateJavadoc -Padd-stylesheet=docs/dark-javadoc.css

      - name: "Copy dark Javadoc to darkdocs"
        run: |
          mkdir -p docs/darkdocs/api
          cp -r build/docs/javadoc/* docs/darkdocs/api

      - name: "Build the documentation"
        run: mkdocs build

      - name: "Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site